### ISSUE TITLE
Wrong chown syntax in the dockerfile

### ISSUE THREAD

**Issue by maurodoglio** [mozilla/sugardough#138] opened 2017-06-27 17:29 UTC
The syntax for chown [here](https://github.com/mozilla/sugardough/blob/master/%7B%7B%20cookiecutter.project_name%20%7D%7D/Dockerfile#L33) seems to be wrong, or at the very least is not the most common way to use it. I was expecting it to use a colon between user and group like 
```bash
RUN chown webdev:webdev -R .
```

**Comment by glogiotatidis** [comment] 2017-07-05 14:23
Syntax is valid and I agree that's not as common but it's quicker and thus I'm used to it. Happy to merge a PR to change this though if you feel like it. I'll close this issue as it's not a bug.

Thanks! 🍺

**Closed as completed by glogiotatidis** 2017-07-05 14:23 UTC
